name: Deploy Laravel/React App

# Trigger the workflow when pushing to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP for Laravel
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Install Composer dependencies for Laravel
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ${{ env.DEPLOY_PATH }}

      # Step 4: Set up Node.js for React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 5: Install npm dependencies and build React assets
      - name: Install NPM dependencies and build assets
        run: |
          npm install
          npm run build
        working-directory: ${{ env.DEPLOY_PATH }}

      # Step 6: Copy the updated files to the deployment directory
      - name: Sync updated files to deployment path
        run: rsync -avz --delete ./ ${{ env.DEPLOY_PATH }}

      # Step 6: Sync updated files to the deployment directory, but exclude vendor and node_modules
      - name: Sync updated files to deployment path
        run: |
          rsync -avz --delete --exclude='vendor' --exclude='node_modules' ./ ${{ env.DEPLOY_PATH }}

      # Step 7: Restart PHP and Nginx services to apply changes
      - name: Restart services
        run: |
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart nginx

      # Stemp 8: Clear laravel cache
      - name: Clear Laravel Cache
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan cache:clear
        working-directory: ${{ env.DEPLOY_PATH }}
