name: Deploy Laravel/React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync updated files to deployment path
        run: |
          rsync -avz \
            --exclude='.env' \
            --exclude='vendor' \
            --exclude='node_modules' \
            --exclude='storage' \
            ./ ${{ env.DEPLOY_PATH }}

      - name: Set up .env file
        run: |
          cp .env.example .env
          # Overwrite sensitive variables using secrets
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          # Add any other environment variables as needed
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM dependencies and build assets
        run: |
          npm install
          NODE_OPTIONS="--max-old-space-size=4096" npm run build
        working-directory: ${{ env.DEPLOY_PATH }}
          
      - name: Run migrations
        run: php artisan migrate --force
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Ensure storage and logs exist
        run: |
          mkdir -p storage/logs
          touch storage/logs/laravel.log
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Set permissions and clear Laravel cache
        run: |
          sudo chown -R githubrunner:githubrunner storage bootstrap/cache
          chmod -R ug+rw storage bootstrap/cache
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan cache:clear
        working-directory: ${{ env.DEPLOY_PATH }}

      - name: Restart services
        run: |
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart nginx
